## Main entry point for yggdrasil-nim.
##
## Async Chronos-based Yggdrasil mesh overlay daemon.
## Supports TCP, TLS, SOCKS5 peer connections via the LinkManager.
## Coordinates:
## - LinkManager (TCP/TLS/SOCKS peer connections)
## - PacketConn (overlay read/write + Ironwood router)
## - TUN adapter (kernel network interface)
## - Proxy server (SOCKS5/HTTP)
## - Admin socket (JSON-RPC)
## - DNS resolver

import std/[os, parseopt, strutils, options, sequtils, httpclient, net]
import chronos
import ./config/configuration
import ./core/[identity, types, peermanager, tree, dht, ckr, publicpeers, yggdebug]
import ./crypto/sodium
import ./ironwood/[wire, router, routerstate, packetconn, asynclink, asyncpeer, routertypes]
import ./admin/api
import ./dns/localdns
import ./transport/proxy
import ./tun/tunadapter
import ./util/bytes as ubytes

const Version* = "0.2.0"

const DefaultPublicPeersUrl* = "https://publicpeers.neilalexander.dev/publicnodes.json"

# ── Key management ───────────────────────────────────────────────────────────

proc loadOrCreateRouterCrypto*(path: string): RouterCrypto =
  ## Load or create Ed25519 keypair for Yggdrasil.
  if fileExists(path):
    for raw in readFile(path).splitLines():
      let line = raw.strip()
      if line.startsWith("secretKey="):
        let bytes = ubytes.fromHex(line.split("=", 1)[1])
        if bytes.len != 64:
          raise newException(ValueError, "invalid Ed25519 secret key length")
        var sk: Ed25519SecretKey
        for i in 0 ..< 64: sk[i] = bytes[i]
        return routerCryptoFromSodium(sk)
    raise newException(ValueError, "key file missing secretKey= line")
  result = newRouterCrypto()
  writeFile(path, "# yggdrasil-nim Ed25519/libsodium key\nsecretKey=" &
    ubytes.toHex(result.secretKey) & "\n")

# ── Utility procs ────────────────────────────────────────────────────────────

proc fetchText(source: string): string =
  if source.startsWith("http://") or source.startsWith("https://"):
    var client = newHttpClient(headers = newHttpHeaders({"User-Agent": "yggdrasil-nim/" & Version}))
    result = client.getContent(source)
  else:
    result = readFile(source)

proc tomlQuote(s: string): string =
  "\"" & s.replace("\\", "\\\\").replace("\"", "\\\"") & "\""

proc canTcpConnect(peer: PeerUri, timeoutMs = 2500): bool =
  if peer.kind notin {tkTcp, tkTls, tkSocks, tkSocksTls, tkWebSocket, tkQuic}: return false
  let host = if peer.kind in {tkSocks, tkSocksTls}:
               peer.host.split('@')[^1].split(':')[0]
             else: peer.host
  let port = if peer.kind in {tkSocks, tkSocksTls}:
               parseInt(peer.host.split('@')[^1].split(':')[1])
             else: peer.port
  let domain = if host.contains(":"): AF_INET6 else: AF_INET
  var sock = newSocket(domain = domain, buffered = false)
  try:
    sock.connect(host, Port(port), timeout = timeoutMs)
    result = true
  except CatchableError:
    result = false
  finally:
    sock.close()

proc addDnsUpstreamsToConfig(path: string, servers: seq[string]) =
  if servers.len == 0: return
  var content = if fileExists(path): readFile(path) else: ""
  var lines = content.splitLines()
  var changed = false
  var foundUpstream = false
  for i in 0 ..< lines.len:
    let stripped = lines[i].strip()
    if stripped.startsWith("upstream") and stripped.contains("[") and stripped.contains("]"):
      foundUpstream = true
      var insert = ""
      for srv in servers:
        if not lines[i].contains(srv):
          if insert.len > 0: insert.add ", "
          insert.add tomlQuote(srv)
      if insert.len > 0:
        let pos = lines[i].rfind(']')
        let needsComma = not lines[i][0 ..< pos].strip().endsWith("[")
        lines[i] = lines[i][0 ..< pos] & (if needsComma: ", " else: "") & insert & lines[i][pos .. ^1]
        changed = true
      break
  if not foundUpstream:
    if content.len > 0 and not content.endsWith("\n"): content.add "\n"
    content.add "\n[DNS]\n"
    content.add "enable = true\n"
    content.add "listen = \"localhost:5053\"\n"
    content.add "upstream = ["
    for i, srv in servers:
      if i > 0: content.add ", "
      content.add tomlQuote(srv)
    content.add "]\n"
    writeFile(path, content)
  else:
    writeFile(path, lines.join("\n") & "\n")

proc writeGeneratedConfig(path: string, peers: seq[PublicPeer], listen: string, keyfile: string,
                          tunEnable, proxyEnable: bool) =
  var toml = "# Generated by yggdrasil-nim --generate-config\n"
  toml.add "# Peer candidates came from the official public peer list, were marked up there,\n"
  toml.add "# and passed a local TCP reachability check where applicable.\n\n"
  toml.add "[Node]\n"
  toml.add "keyfile = " & tomlQuote(keyfile) & "\n"
  toml.add "name = \"generated-node\"\n\n"
  toml.add "[Peers]\n"
  toml.add "static = [\n"
  for p in peers:
    toml.add "  " & tomlQuote(p.uri) & ", # " & p.region & " response_ms=" & $p.responseMs & "\n"
  toml.add "]\n"
  toml.add "multicast = false\n"
  toml.add "peerExchange = true\n"
  toml.add "publicPeerLists = [" & tomlQuote(DefaultPublicPeersUrl) & "]\n\n"
  toml.add "[TUN]\n"
  toml.add "enable = " & (if tunEnable: "true" else: "false") & "\n"
  toml.add "name = \"ygg0\"\n"
  toml.add "mtu = 65535\n\n"
  toml.add "[Proxy]\n"
  toml.add "enable = " & (if proxyEnable: "true" else: "false") & "\n"
  toml.add "# localhost binds both 127.0.0.1 and ::1 in the Nim backend.\n"
  toml.add "listen = " & tomlQuote(listen) & "\n"
  toml.add "socks5 = true\n"
  toml.add "http = true\n\n"
  toml.add "[DNS]\n"
  toml.add "enable = true\n"
  toml.add "# localhost binds both 127.0.0.1 and ::1 in the Nim DNS backend.\n"
  toml.add "listen = \"localhost:5053\"\n"
  toml.add "internalDomain = \".yg\"\n"
  toml.add "hostsFile = \"hosts.yg\"\n"
  toml.add "# Public resolvers work before the overlay data plane exists. The Yggdrasil DNS\n"
  toml.add "# servers below can be moved before them once overlay routing is implemented:\n"
  toml.add "# [308:c8:48:45::]:53, [308:25:40:bd::]:53, [308:62:45:62::]:53, [308:84:68:55::]:53\n"
  toml.add "upstream = [\"1.1.1.1:53\", \"8.8.8.8:53\", \"[308:c8:48:45::]:53\", \"[308:25:40:bd::]:53\", \"[308:62:45:62::]:53\", \"[308:84:68:55::]:53\"]\n\n"
  toml.add "[Admin]\n"
  toml.add "listen = [\"tcp://127.0.0.1:9001\"]\n"
  toml.add "keepalive = true\n\n"
  toml.add "[Crypto]\n"
  toml.add "postQuantum = false\n"
  toml.add "kem = \"none\"\n"
  toml.add "aead = \"development-only\"\n"
  toml.add "perHopProtection = false\n"
  writeFile(path, toml)

# ── Data plane: TUN ↔ PacketConn ────────────────────────────────────────────

proc tunToOverlay(tun: TunAdapter, pc: PacketConn) {.async.} =
  ## Read packets from TUN, write to overlay via PacketConn.
  ## This is the "ingress" path: kernel → overlay.
  while tun.running:
    try:
      let packet = await tun.readPacket()
      if packet.len == 0: continue
      
      # Parse the destination from the IP packet
      let version = packet[0] shr 4
      var destKey: NodeId
      
      if version == 6 and packet.len >= 40:
        # IPv6: destination is in bytes [24..39].
        # For Yggdrasil, the 200::/7 IPv6 address encodes a prefix of the NodeId.
        var destAddr: IPv6Address
        for i in 0 ..< 16: destAddr[i] = packet[24 + i]
        destKey = keyPrefixForYggAddress(destAddr)
        stderr.writeLine "[dataplane] TUN->overlay dest=" & short(destKey) & " pktLen=" & $packet.len
      elif version == 4 and packet.len >= 20:
        # IPv4: we don't route IPv4 directly - skip for now
        continue
      else:
        continue
      
      # Prepend typeSessionTraffic byte (0x01) to match Go yggdrasil's
      # core.WriteTo which wraps every TUN packet with this type marker.
      # Go: typeSessionDummy=0, typeSessionTraffic=1, typeSessionProto=2
      var framed = newSeq[byte](packet.len + 1)
      framed[0] = 0x01'u8  # typeSessionTraffic
      for i in 0 ..< packet.len: framed[1 + i] = packet[i]
      await pc.writeTo(destKey, framed)
    except CancelledError:
      break
    except CatchableError as e:
      if not tun.running: break
      # Log but don't die on individual packet errors
      await sleepAsync(chronos.milliseconds(1))

proc overlayToTun(pc: PacketConn, tun: TunAdapter) {.async.} =
  ## Read deliveries from PacketConn, write to TUN.
  ## This is the "egress" path: overlay -> kernel.
  var buf = newSeq[byte](65536)
  while tun.running:
    try:
      let (n, source) = await pc.readFrom(addr buf[0], buf.len)
      if n == 0: continue
      # Strip the typeSessionTraffic byte (0x01) that Go yggdrasil prepends.
      var offset = 0
      if n > 0 and buf[0] == 0x01'u8:
        offset = 1
      let pktLen = n - offset
      if pktLen <= 0: continue
      stderr.writeLine "[dataplane] overlay->TUN src=" & short(source) & " n=" & $pktLen
      await tun.writePacket(buf[offset ..< n])
    except CancelledError:
      break
    except CatchableError as e:
      if not tun.running: break
      await sleepAsync(chronos.milliseconds(1))

# ── Async daemon ─────────────────────────────────────────────────────────────

proc runDaemon(listenAddrs, peerUris: seq[string], keyfile: string,
               tunEnable, proxyEnable: bool,
               proxyListen: string, dnsEnable: bool,
               tunName: string, tunMtu: int) {.async.} =
  var crypto: RouterCrypto
  {.cast(gcsafe).}:
    try:
      crypto = loadOrCreateRouterCrypto(keyfile)
    except Exception:
      echo "failed to load key: ", getCurrentExceptionMsg()
      return

  let address = deriveYggAddress(crypto.publicKey)
  let ipv6Str = toIPv6String(address)
  echo "yggdrasil-nim ", Version, " starting..."
  echo "publicKey=", short(crypto.publicKey)
  echo "address=", ipv6Str

  var packetConn: PacketConn
  {.cast(gcsafe).}:
    try:
      packetConn = newPacketConn(crypto)
    except Exception:
      echo "failed to create PacketConn: ", getCurrentExceptionMsg()
      return
  await packetConn.start()

  let linkConfig = LinkConfig(
    listenAddrs: listenAddrs,
    peerUris: peerUris,
    password: @[],
  )
  let linkMgr = newLinkManager(crypto, packetConn, linkConfig)
  await linkMgr.start()

  # ── TUN adapter ──────────────────────────────────────────────────────────
  var tun: TunAdapter = nil
  if tunEnable:
    try:
      let tunCfg = TunConfig(
        enable: true,
        name: if tunName.len > 0: tunName else: "ygg0",
        mtu: if tunMtu > 0: tunMtu else: 65535,
        ipv6: ipv6Str,
        ipv4: "",
      )
      tun = openTun(tunCfg)
      tun.configureInterface(ipv6Str, tunCfg.mtu)
      tun.configureRoutes()
      tun.startIo()
      echo "TUN interface ", tun.ifName, " configured with ", ipv6Str, "/7"
      
      # Start data plane
      asyncSpawn tunToOverlay(tun, packetConn)
      asyncSpawn overlayToTun(packetConn, tun)
      echo "Data plane active: TUN ↔ PacketConn"
    except CatchableError as e:
      echo "TUN setup failed: ", e.msg
      echo "Continuing without TUN (proxy-only mode)"

  # ── Proxy ────────────────────────────────────────────────────────────────
  if proxyEnable:
    var ps = ProxyServer(
      cfg: ProxyConfig(enabled: true, listen: proxyListen, socks5: true, http: true),
      running: false,
    )
    ps.start()
    echo "Proxy listening at ", proxyListen

  # ── DNS ──────────────────────────────────────────────────────────────────
  if dnsEnable:
    var dns = initLocalDnsServer(LocalDnsConfig(
      enable: true, listen: "localhost:5053",
      internalDomain: ".yg", hostsPath: "hosts.yg",
      upstream: @["1.1.1.1:53", "8.8.8.8:53"],
    ))
    dns.start()
    echo "DNS resolver listening at localhost:5053"

  echo "Daemon running. Press Ctrl+C to exit."
  echo "Peers: ", peerUris.len, " configured | TUN: ", if tun != nil: tun.ifName else: "disabled"

  while true:
    await sleepAsync(chronos.milliseconds(1000))

# ── CLI ──────────────────────────────────────────────────────────────────────

proc usage() =
  echo """
yggdrasil-nim - Yggdrasil mesh overlay daemon (Chronos async)

Usage:
  yggdrasil-nim [options]

Options:
  --config=PATH           TOML config file
  --keyfile=PATH          Override Node.keyfile
  --listen=ADDR           Listen address (repeatable, e.g. "tcp://0.0.0.0:12345")
  --peer=URI              Peer URI to connect to (repeatable)
                          Supported: tcp://, tls://, ws://, wss://, quic://,
                                     socks://, sockstls://
                          URI params: ?key=, ?sni=, ?priority=, ?password=, ?maxbackoff=
  --no-tun                Disable TUN mode
  --proxy                 Enable SOCKS5/HTTP proxy
  --socks5-addr=ADDR      Enable proxy and set SOCKS5/HTTP listen address
  --self                  Print node identity and exit
  --version               Print version and exit
  --run                   Start the daemon

  --check-public-peers=URL_OR_FILE
                          Fetch/read and parse official public peer JSON, then exit
  --generate-config=PATH  Generate TOML config with reachable up public peers
  --generate-key=PATH     Generate/reuse Ed25519 Yggdrasil key file and print address
  --generate-proxy-config=PATH
                          Backward-compatible alias for --generate-config + --proxy-mode
  --proxy-mode            Proxy only, no TUN
  --tun-mode              TUN only, no proxy
  --tun-proxy-mode        Both TUN and proxy
  --peer-count=N          Number of reachable up peers in generated config (default: 8)
  --add-dns=ADDR          Add DNS upstream to --config file and exit (repeatable)
  --admin-json=JSON       Dispatch one JSON-RPC admin request and exit
  -h, --help              Show help

Peer URI examples:
  tcp://1.2.3.4:12345
  tls://example.com:443
  tls://1.2.3.4:443?sni=example.com
  ws://example.com:80/path
  wss://example.com:443/path
  quic://example.com:443
  socks://proxy.local:1080/1.2.3.4:12345
  sockstls://user:pass@proxy.local:1080/example.com:443?sni=example.com
  tcp://1.2.3.4:12345?key=abcdef1234...&priority=1&password=secret
"""

proc main() =
  var configPath = if fileExists("config.example.toml"): "config.example.toml" else: ""
  var forceProxy = false
  var noTun = false
  var modeProxyOnly = false
  var modeTunOnly = false
  var modeTunProxy = false
  var printSelf = false
  var printVersion = false
  var adminJson = ""
  var runFlag = false
  var keyOverride = ""
  var socks5Addr = ""
  var publicPeersSource = ""
  var generateConfigPath = ""
  var generateKeyPath = ""
  var peerCount = 8
  var listenAddrs: seq[string]
  var peerUris: seq[string]
  var dnsToAdd: seq[string]
  var tunNameOverride = ""

  var p = initOptParser(commandLineParams())
  for kind, key, val in p.getopt():
    case kind
    of cmdLongOption, cmdShortOption:
      case key
      of "config": configPath = val
      of "tun-name": tunNameOverride = val
      of "keyfile": keyOverride = val
      of "listen": listenAddrs.add val
      of "peer": peerUris.add val
      of "proxy": forceProxy = true
      of "proxy-mode":
        modeProxyOnly = true
        forceProxy = true
        noTun = true
      of "tun-mode":
        modeTunOnly = true
      of "tun-proxy-mode", "tun-with-proxy":
        modeTunProxy = true
        forceProxy = true
      of "socks5-addr":
        forceProxy = true
        socks5Addr = val
      of "no-tun": noTun = true
      of "self": printSelf = true
      of "version": printVersion = true
      of "check-public-peers": publicPeersSource = val
      of "generate-config": generateConfigPath = val
      of "generate-key": generateKeyPath = val
      of "generate-proxy-config":
        generateConfigPath = val
        modeProxyOnly = true
        forceProxy = true
        noTun = true
      of "peer-count": peerCount = parseInt(val)
      of "add-dns": dnsToAdd.add val
      of "admin-json": adminJson = val
      of "run": runFlag = true
      of "h", "help": usage(); return
      else:
        echo "unknown option: ", key
    of cmdArgument:
      discard
    of cmdEnd:
      discard

  if printVersion:
    echo "yggdrasil-nim ", Version
    return

  if generateKeyPath.len > 0:
    try:
      let c = loadOrCreateRouterCrypto(generateKeyPath)
      echo "keyfile=", generateKeyPath
      echo "publicKey=", toHex(c.publicKey)
      echo "address=", toIPv6String(deriveYggAddress(c.publicKey))
    except CatchableError as e:
      quit "generate-key failed: " & e.msg, 1
    return

  if dnsToAdd.len > 0:
    addDnsUpstreamsToConfig(configPath, dnsToAdd)
    echo "added ", dnsToAdd.len, " DNS upstream(s) to ", configPath
    return

  if publicPeersSource.len > 0:
    let content = fetchText(publicPeersSource)
    let summary = summarizePublicPeersJson(content)
    let peers = parsePublicPeersJson(content, onlyUp = true)
    echo "publicPeers ", summary
    for i in 0 ..< min(10, peers.len):
      let p = peers[i]
      echo p.uri, " region=", p.region, " up=", p.up, " responseMs=", p.responseMs
    return

  if generateConfigPath.len > 0:
    if peerCount <= 0: quit "--peer-count must be positive", 2
    let source = if publicPeersSource.len > 0: publicPeersSource else: DefaultPublicPeersUrl
    let content = fetchText(source)
    let allPeers = parsePublicPeersJson(content, onlyUp = true)
    var selected: seq[PublicPeer]
    for p in allPeers:
      if p.parsed.kind notin {tkTcp, tkTls, tkQuic, tkWebSocket}: continue
      if not canTcpConnect(p.parsed): continue
      selected.add p
      if selected.len >= peerCount: break
    if selected.len == 0: quit "no reachable TCP/TLS public peers found", 2
    let listen = if socks5Addr.len > 0: socks5Addr else: "localhost:1080"
    let keyfile = if keyOverride.len > 0: keyOverride else: "yggdrasil.key"
    try:
      discard loadOrCreateRouterCrypto(keyfile)
    except CatchableError as e:
      quit "could not create keyfile " & keyfile & ": " & e.msg, 1
    var tunEnable = false
    var proxyEnable = true
    if modeTunOnly:
      tunEnable = true
      proxyEnable = false
    elif modeTunProxy:
      tunEnable = true
      proxyEnable = true
    elif modeProxyOnly:
      tunEnable = false
      proxyEnable = true
    writeGeneratedConfig(generateConfigPath, selected, listen, keyfile, tunEnable, proxyEnable)
    echo "generated ", generateConfigPath, " with ", selected.len, " reachable up public peers; tun=", tunEnable, " proxy=", proxyEnable, " proxy listen=", listen
    return

  # Load config
  var cfg = loadConfig(configPath)
  if keyOverride.len > 0: cfg.node.keyfile = keyOverride
  if modeProxyOnly:
    cfg.proxy.enable = true
    cfg.tun.enable = false
  elif modeTunOnly:
    cfg.proxy.enable = false
    cfg.tun.enable = true
  elif modeTunProxy:
    cfg.proxy.enable = true
    cfg.tun.enable = true
  if forceProxy: cfg.proxy.enable = true
  if socks5Addr.len > 0: cfg.proxy.listen = socks5Addr
  if noTun: cfg.tun.enable = false

  # Merge CLI peer URIs with config
  if peerUris.len == 0: peerUris = cfg.peers.staticPeers
  if listenAddrs.len == 0:
    if cfg.admin.listen.len > 0:
      for a in cfg.admin.listen:
        try:
          let parsed = parsePeerUri(a)
          if parsed.kind == tkTcp:
            listenAddrs.add a
        except CatchableError:
          discard
    if listenAddrs.len == 0:
      listenAddrs.add("tcp://0.0.0.0:12345")

  # Print identity and exit
  if printSelf:
    try:
      let crypto = loadOrCreateRouterCrypto(cfg.node.keyfile)
      echo "publicKey=", toHex(crypto.publicKey)
      echo "address=", toIPv6String(deriveYggAddress(crypto.publicKey))
    except CatchableError as e:
      echo "error: ", e.msg
    return

  # Admin JSON-RPC
  if adminJson.len > 0:
    let id = loadOrCreateIdentity(cfg.node.keyfile)
    var tr = initTree(id.publicKey)
    var dd = initDht(id.publicKey)
    dd.refreshSelf(tr.selfCoords, tr.revision)
    var routes = initCkrTable()
    var pm = initPeerManager(defaultPeerManagerConfig())
    var admin = initAdminContext(id, tr, dd, routes, pm, cfg.admin.keepalive)
    echo admin.dispatchRpc(adminJson)
    return

  if not runFlag:
    echo "Use --run to start the daemon."
    return

  # Run async daemon
  let proxyListen = if socks5Addr.len > 0: socks5Addr else: cfg.proxy.listen
  let tunName = if tunNameOverride.len > 0: tunNameOverride else: cfg.tun.name
  waitFor runDaemon(
    listenAddrs, peerUris, cfg.node.keyfile,
    cfg.tun.enable, cfg.proxy.enable,
    proxyListen, cfg.dns.enable,
    tunName, cfg.tun.mtu,
  )

when isMainModule:
  main()
