## Main entry point for yggdrasil-nim.

import std/[os, parseopt, strutils, httpclient, net]
import ./config/configuration
import ./core/[identity, tree, dht, ckr, peermanager, publicpeers, yggdebug, types]
import ./ironwood/link
import ./admin/api
import ./dns/localdns
import ./transport/proxy
import ./tun/tunadapter

const Version* = "0.1.0"
const DefaultPublicPeersUrl* = "https://publicpeers.neilalexander.dev/publicnodes.json"

proc fetchText(source: string): string =
  if source.startsWith("http://") or source.startsWith("https://"):
    var client = newHttpClient(headers = newHttpHeaders({"User-Agent": "yggdrasil-nim/" & Version}))
    result = client.getContent(source)
  else:
    result = readFile(source)

proc tomlQuote(s: string): string =
  "\"" & s.replace("\\", "\\\\").replace("\"", "\\\"") & "\""

proc canTcpConnect(peer: PeerUri, timeoutMs = 2500): bool =
  if peer.kind notin {tkTcp, tkTls, tkWebSocket}: return false
  let domain = if peer.host.contains(":"): AF_INET6 else: AF_INET
  var sock = newSocket(domain = domain, buffered = false)
  try:
    sock.connect(peer.host, Port(peer.port), timeout = timeoutMs)
    result = true
  except CatchableError:
    result = false
  finally:
    sock.close()

proc addDnsUpstreamsToConfig(path: string, servers: seq[string]) =
  if servers.len == 0: return
  var content = if fileExists(path): readFile(path) else: ""
  var lines = content.splitLines()
  var changed = false
  var foundUpstream = false
  for i in 0 ..< lines.len:
    let stripped = lines[i].strip()
    if stripped.startsWith("upstream") and stripped.contains("[") and stripped.contains("]"):
      foundUpstream = true
      var insert = ""
      for srv in servers:
        if not lines[i].contains(srv):
          if insert.len > 0: insert.add ", "
          insert.add tomlQuote(srv)
      if insert.len > 0:
        let pos = lines[i].rfind(']')
        let needsComma = not lines[i][0 ..< pos].strip().endsWith("[")
        lines[i] = lines[i][0 ..< pos] & (if needsComma: ", " else: "") & insert & lines[i][pos .. ^1]
        changed = true
      break
  if not foundUpstream:
    if content.len > 0 and not content.endsWith("\n"): content.add "\n"
    content.add "\n[DNS]\n"
    content.add "enable = true\n"
    content.add "listen = \"localhost:5053\"\n"
    content.add "upstream = ["
    for i, srv in servers:
      if i > 0: content.add ", "
      content.add tomlQuote(srv)
    content.add "]\n"
    writeFile(path, content)
  else:
    writeFile(path, lines.join("\n") & "\n")

proc writeGeneratedConfig(path: string, peers: seq[PublicPeer], listen: string, keyfile: string,
                          tunEnable, proxyEnable: bool) =
  var toml = "# Generated by yggdrasil-nim --generate-config\n"
  toml.add "# Peer candidates came from the official public peer list, were marked up there,\n"
  toml.add "# and passed a local TCP reachability check where applicable.\n\n"
  toml.add "[Node]\n"
  toml.add "keyfile = " & tomlQuote(keyfile) & "\n"
  toml.add "name = \"generated-node\"\n\n"
  toml.add "[Peers]\n"
  toml.add "static = [\n"
  for p in peers:
    toml.add "  " & tomlQuote(p.uri) & ", # " & p.region & " response_ms=" & $p.responseMs & "\n"
  toml.add "]\n"
  toml.add "multicast = false\n"
  toml.add "peerExchange = true\n"
  toml.add "publicPeerLists = [" & tomlQuote(DefaultPublicPeersUrl) & "]\n\n"
  toml.add "[TUN]\n"
  toml.add "enable = " & (if tunEnable: "true" else: "false") & "\n"
  toml.add "name = \"yggdrasil0\"\n"
  toml.add "mtu = 65535\n\n"
  toml.add "[Proxy]\n"
  toml.add "enable = " & (if proxyEnable: "true" else: "false") & "\n"
  toml.add "# localhost binds both 127.0.0.1 and ::1 in the Nim backend.\n"
  toml.add "listen = " & tomlQuote(listen) & "\n"
  toml.add "socks5 = true\n"
  toml.add "http = true\n\n"
  toml.add "[DNS]\n"
  toml.add "enable = true\n"
  toml.add "# localhost binds both 127.0.0.1 and ::1 in the Nim DNS backend.\n"
  toml.add "listen = \"localhost:5053\"\n"
  toml.add "internalDomain = \".yg\"\n"
  toml.add "hostsFile = \"hosts.yg\"\n"
  toml.add "# Public resolvers work before the overlay data plane exists. The Yggdrasil DNS\n"
  toml.add "# servers below can be moved before them once overlay routing is implemented:\n"
  toml.add "# [308:c8:48:45::]:53, [308:25:40:bd::]:53, [308:62:45:62::]:53, [308:84:68:55::]:53\n"
  toml.add "upstream = [\"1.1.1.1:53\", \"8.8.8.8:53\", \"[308:c8:48:45::]:53\", \"[308:25:40:bd::]:53\", \"[308:62:45:62::]:53\", \"[308:84:68:55::]:53\"]\n\n"
  toml.add "[Admin]\n"
  toml.add "listen = [\"tcp://127.0.0.1:9001\"]\n"
  toml.add "keepalive = true\n\n"
  toml.add "[Crypto]\n"
  toml.add "postQuantum = false\n"
  toml.add "kem = \"none\"\n"
  toml.add "aead = \"development-only\"\n"
  toml.add "perHopProtection = false\n"
  writeFile(path, toml)

proc usage() =
  echo """
yggdrasil-nim - Yggdrasil-style mesh overlay daemon

Options:
  --config=PATH        TOML config file (default: config.example.toml if present)
  --keyfile=PATH       Override Node.keyfile
  --proxy              Force unprivileged proxy mode
  --socks5-addr=ADDR   Enable proxy mode and set SOCKS5/HTTP listen address
  --no-tun             Disable TUN mode
  --self               Print node identity and exit
  --version            Print version and exit
  --check-public-peers=URL_OR_FILE
                        Fetch/read and parse official public peer JSON, then exit
  --generate-config=PATH
                        Generate TOML config with reachable up public peers
  --generate-key=PATH  Generate/reuse Ed25519 Yggdrasil key file and print address
  --generate-proxy-config=PATH
                        Backward-compatible alias for --generate-config + --proxy-mode
  --proxy-mode         Generated/runtime mode: proxy only, no TUN
  --tun-mode           Generated/runtime mode: TUN only, no proxy
  --tun-proxy-mode     Generated/runtime mode: both TUN and proxy
  --peer-count=N       Number of reachable up peers to put in generated config (default: 8)
  --debug-handshake    Try Yggdrasil TCP metadata handshakes to configured/debug peers
  --debug-ironwood     After meta, probe post-handshake Ironwood frames for tcp peers
  --debug-peer=URI     Peer URI to test in debug handshake/probe mode (repeatable)
  --debug-target=IPv6  Target Yggdrasil IPv6 for debug PathLookup probe
  --handshake-count=N  Max debug handshakes/probes to attempt (default: 3)
  --debug-keyfile=PATH Ed25519 PEM key for debug handshakes (generated if absent)
  --add-dns=ADDR       Add DNS upstream to --config file and exit (repeatable)
  --admin-json=JSON    Dispatch one JSON-RPC admin request and exit
  --run                Initialize adapters and stay in daemon skeleton
  -h, --help           Show help
"""

proc main() =
  var configPath = if fileExists("config.example.toml"): "config.example.toml" else: ""
  var forceProxy = false
  var noTun = false
  var modeProxyOnly = false
  var modeTunOnly = false
  var modeTunProxy = false
  var printSelf = false
  var printVersion = false
  var adminJson = ""
  var runLoop = false
  var keyOverride = ""
  var socks5Addr = ""
  var publicPeersSource = ""
  var generateConfigPath = ""
  var generateKeyPath = ""
  var peerCount = 8
  var debugHandshake = false
  var debugIronwood = false
  var debugPeers: seq[string]
  var debugTarget = ""
  var handshakeCount = 3
  var debugKeyFile = "yggdrasil-debug-ed25519.pem"
  var ironwoodRun = false
  var ironwoodSeconds = 0
  var ironwoodKeyFile = ""
  var dnsToAdd: seq[string]

  var p = initOptParser(commandLineParams())
  for kind, key, val in p.getopt():
    case kind
    of cmdLongOption, cmdShortOption:
      case key
      of "config": configPath = val
      of "keyfile": keyOverride = val
      of "proxy": forceProxy = true
      of "proxy-mode":
        modeProxyOnly = true
        forceProxy = true
        noTun = true
      of "tun-mode":
        modeTunOnly = true
      of "tun-proxy-mode", "tun-with-proxy":
        modeTunProxy = true
        forceProxy = true
      of "socks5-addr":
        forceProxy = true
        socks5Addr = val
      of "no-tun": noTun = true
      of "self": printSelf = true
      of "version": printVersion = true
      of "check-public-peers": publicPeersSource = val
      of "generate-config": generateConfigPath = val
      of "generate-key": generateKeyPath = val
      of "generate-proxy-config":
        generateConfigPath = val
        modeProxyOnly = true
        forceProxy = true
        noTun = true
      of "peer-count": peerCount = parseInt(val)
      of "debug-handshake": debugHandshake = true
      of "debug-ironwood":
        debugHandshake = true
        debugIronwood = true
      of "debug-peer": debugPeers.add val
      of "debug-target": debugTarget = val
      of "handshake-count": handshakeCount = parseInt(val)
      of "debug-keyfile": debugKeyFile = val
      of "ironwood-run": ironwoodRun = true
      of "ironwood-seconds": ironwoodSeconds = parseInt(val)
      of "ironwood-keyfile": ironwoodKeyFile = val
      of "add-dns": dnsToAdd.add val
      of "admin-json": adminJson = val
      of "run": runLoop = true
      of "h", "help": usage(); return
      else:
        quit "unknown option: " & key, 2
    of cmdArgument:
      discard
    of cmdEnd:
      discard

  if printVersion:
    echo "yggdrasil-nim ", Version
    return

  if generateKeyPath.len > 0:
    try:
      let c = loadOrCreateRouterCrypto(generateKeyPath)
      echo "keyfile=", generateKeyPath
      echo "publicKey=", toHex(c.publicKey)
      echo "address=", toIPv6String(deriveYggAddress(c.publicKey))
    except CatchableError as e:
      quit "generate-key failed: " & e.msg, 1
    return

  if dnsToAdd.len > 0:
    addDnsUpstreamsToConfig(configPath, dnsToAdd)
    echo "added ", dnsToAdd.len, " DNS upstream(s) to ", configPath
    return

  if publicPeersSource.len > 0:
    let content = fetchText(publicPeersSource)
    let summary = summarizePublicPeersJson(content)
    let peers = parsePublicPeersJson(content, onlyUp = true)
    echo "publicPeers ", summary
    for i in 0 ..< min(10, peers.len):
      let p = peers[i]
      echo p.uri, " region=", p.region, " up=", p.up, " responseMs=", p.responseMs
    return

  if generateConfigPath.len > 0:
    if peerCount <= 0: quit "--peer-count must be positive", 2
    let source = if publicPeersSource.len > 0: publicPeersSource else: DefaultPublicPeersUrl
    let content = fetchText(source)
    let allPeers = parsePublicPeersJson(content, onlyUp = true)
    var selected: seq[PublicPeer]
    for p in allPeers:
      ## The generated config prefers plain tcp:// peers because the debug
      ## metadata handshake implemented here currently targets yggdrasil-go's
      ## TCP link carrier. TLS/QUIC/WS carriers need their own wrappers first.
      if p.parsed.kind != tkTcp: continue
      if not canTcpConnect(p.parsed): continue
      selected.add p
      if selected.len >= peerCount: break
    if selected.len == 0: quit "no reachable TCP/TLS/WS public peers found", 2
    let listen = if socks5Addr.len > 0: socks5Addr else: "localhost:1080"
    let keyfile = if keyOverride.len > 0: keyOverride else: "yggdrasil.key"
    try:
      discard loadOrCreateRouterCrypto(keyfile)
    except CatchableError as e:
      quit "could not create keyfile " & keyfile & ": " & e.msg, 1
    var tunEnable = false
    var proxyEnable = true
    if modeTunOnly:
      tunEnable = true
      proxyEnable = false
    elif modeTunProxy:
      tunEnable = true
      proxyEnable = true
    elif modeProxyOnly:
      tunEnable = false
      proxyEnable = true
    writeGeneratedConfig(generateConfigPath, selected, listen, keyfile, tunEnable, proxyEnable)
    echo "generated ", generateConfigPath, " with ", selected.len, " reachable up public peers; tun=", tunEnable, " proxy=", proxyEnable, " proxy listen=", listen
    return

  var cfg = loadConfig(configPath)
  if keyOverride.len > 0: cfg.node.keyfile = keyOverride
  if modeProxyOnly:
    cfg.proxy.enable = true
    cfg.tun.enable = false
  elif modeTunOnly:
    cfg.proxy.enable = false
    cfg.tun.enable = true
  elif modeTunProxy:
    cfg.proxy.enable = true
    cfg.tun.enable = true
  if forceProxy: cfg.proxy.enable = true
  if socks5Addr.len > 0: cfg.proxy.listen = socks5Addr
  if noTun: cfg.tun.enable = false

  let id = loadOrCreateIdentity(cfg.node.keyfile)
  var tr = initTree(id.publicKey)
  var dd = initDht(id.publicKey)
  dd.refreshSelf(tr.selfCoords, tr.revision)
  var routes = initCkrTable()
  var pm = initPeerManager(defaultPeerManagerConfig())
  for uri in cfg.peers.staticPeers:
    discard pm.addPeer(uri, psStatic, allowAutoDial = true)

  if ironwoodRun:
    var candidates = debugPeers
    if candidates.len == 0: candidates = cfg.peers.staticPeers
    var selected = ""
    for uri in candidates:
      try:
        if parsePeerUri(uri).kind == tkTcp:
          selected = uri
          break
      except CatchableError:
        discard
    if selected.len == 0: quit "ironwood-run: no tcp:// peer candidate found", 2
    let iwKey = if ironwoodKeyFile.len > 0: ironwoodKeyFile else: cfg.node.keyfile
    echo "ironwood-run starting peer=", selected, " keyfile=", iwKey,
         " seconds=", ironwoodSeconds
    for item in runTcpIronwoodLink(LinkRunConfig(uri: selected, keyFile: iwKey,
                                                seconds: ironwoodSeconds, target: debugTarget,
                                                timeoutMs: 7000)):
      echo item.kind, " ", item.message
    return

  if debugHandshake:
    var candidates = debugPeers
    if candidates.len == 0: candidates = cfg.peers.staticPeers
    var attempted = 0
    var okCount = 0
    for uri in candidates:
      if attempted >= handshakeCount: break
      var parsedOk = true
      try:
        if parsePeerUri(uri).kind != tkTcp: parsedOk = false
      except CatchableError:
        parsedOk = false
      if not parsedOk: continue
      inc attempted
      if debugIronwood:
        try:
          for line in probeYggdrasilTcpIronwood(uri, debugKeyFile, seconds = 8, targetAddress = debugTarget):
            echo uri, " ", line
          inc okCount
        except CatchableError as e:
          echo "FAIL ", uri, " ironwood-probe error=", e.msg
      else:
        let r = performYggdrasilTcpMetadataHandshake(uri, debugKeyFile)
        echo r.summary()
        if r.ok: inc okCount
    if attempted == 0:
      quit "debug handshake: no tcp:// candidates to test", 2
    if okCount == 0:
      quit "debug handshake: all attempts failed", 1
    echo "debug handshake complete: ", okCount, "/", attempted, " successful"
    return

  if printSelf:
    echo id.describe()
    return

  var admin = initAdminContext(id, tr, dd, routes, pm, cfg.admin.keepalive)
  if adminJson.len > 0:
    echo admin.dispatchRpc(adminJson)
    return

  var tun = initTunAdapter(TunConfig(enable: cfg.tun.enable, name: cfg.tun.name,
                                     mtu: cfg.tun.mtu, ipv6: cfg.tun.ipv6,
                                     ipv4: cfg.tun.ipv4))
  var ps = ProxyServer(cfg: ProxyConfig(enabled: cfg.proxy.enable, listen: cfg.proxy.listen,
                                        socks5: cfg.proxy.socks5, http: cfg.proxy.http),
                       running: false)
  var dns = initLocalDnsServer(LocalDnsConfig(enable: cfg.dns.enable, listen: cfg.dns.listen,
                                             internalDomain: cfg.dns.internalDomain,
                                             hostsPath: cfg.dns.hostsFile,
                                             upstream: cfg.dns.upstream))

  echo "yggdrasil-nim initialized: ", id.describe()
  echo "coordinates=", coordToString(tr.selfCoords), " root=", short(tr.rootId)
  echo "knownPeers=", pm.knownUris().len, " tun=", cfg.tun.enable, " proxy=", cfg.proxy.enable,
       " dns=", cfg.dns.enable

  if cfg.tun.enable:
    try:
      tun.open()
      echo "TUN adapter initialized for platform ", tun.platform, " (driver backend stub)"
    except CatchableError as e:
      echo "TUN disabled: ", e.msg

  if cfg.proxy.enable:
    ps.start()
    echo "Proxy listening boundary initialized at ", cfg.proxy.listen

  if cfg.dns.enable:
    dns.start()
    echo "DNS resolver boundary initialized at ", cfg.dns.listen

  if runLoop:
    echo "Daemon skeleton running. Press Ctrl+C to exit."
    while true:
      sleep(1000)
  else:
    echo "Use --run to keep the daemon skeleton running."

when isMainModule:
  main()
